"""initial schema separation: asset_manager and helpdesk schemas

Revision ID: 6f17dc20975e
Revises: 
Create Date: 2026-03-17 11:23:02.855075

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6f17dc20975e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['helpdesk.categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='helpdesk'
    )
    with op.batch_alter_table('categories', schema='helpdesk') as batch_op:
        batch_op.create_index(batch_op.f('ix_helpdesk_categories_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_helpdesk_categories_slug'), ['slug'], unique=True)

    op.create_table('canned_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('shortcut', sa.String(length=50), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('use_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['helpdesk.categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shortcut'),
    schema='helpdesk'
    )
    op.create_table('sla_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('first_response_hours', sa.Float(), nullable=False),
    sa.Column('resolution_hours', sa.Float(), nullable=False),
    sa.Column('business_hours_only', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['helpdesk.categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='helpdesk'
    )
    with op.batch_alter_table('sla_policies', schema='helpdesk') as batch_op:
        batch_op.create_index(batch_op.f('ix_helpdesk_sla_policies_category_id'), ['category_id'], unique=False)

    op.create_table('tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=20), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('subcategory_id', sa.Integer(), nullable=True),
    sa.Column('requester_name', sa.String(length=255), nullable=False),
    sa.Column('requester_email', sa.String(length=255), nullable=False),
    sa.Column('requester_phone', sa.String(length=50), nullable=True),
    sa.Column('assigned_to', sa.String(length=255), nullable=True),
    sa.Column('assigned_to_email', sa.String(length=255), nullable=True),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('sla_policy_id', sa.Integer(), nullable=True),
    sa.Column('first_response_due', sa.DateTime(), nullable=True),
    sa.Column('resolution_due', sa.DateTime(), nullable=True),
    sa.Column('first_responded_at', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('email_message_id', sa.String(length=500), nullable=True),
    sa.Column('email_thread_id', sa.String(length=500), nullable=True),
    sa.Column('email_cc', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('solved_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['asset_manager.assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['category_id'], ['helpdesk.categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sla_policy_id'], ['helpdesk.sla_policies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subcategory_id'], ['helpdesk.categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='helpdesk'
    )
    with op.batch_alter_table('tickets', schema='helpdesk') as batch_op:
        batch_op.create_index(batch_op.f('ix_helpdesk_tickets_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_helpdesk_tickets_assigned_to_email'), ['assigned_to_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_helpdesk_tickets_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_helpdesk_tickets_email_message_id'), ['email_message_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_helpdesk_tickets_email_thread_id'), ['email_thread_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_helpdesk_tickets_number'), ['number'], unique=True)
        batch_op.create_index(batch_op.f('ix_helpdesk_tickets_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_helpdesk_tickets_requester_email'), ['requester_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_helpdesk_tickets_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_helpdesk_tickets_subcategory_id'), ['subcategory_id'], unique=False)

    op.create_table('email_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('direction', sa.String(length=5), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=True),
    sa.Column('message_id', sa.String(length=500), nullable=True),
    sa.Column('from_addr', sa.String(length=500), nullable=True),
    sa.Column('to_addr', sa.Text(), nullable=True),
    sa.Column('subject', sa.String(length=1000), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('raw_snippet', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['helpdesk.tickets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id'),
    schema='helpdesk'
    )
    with op.batch_alter_table('email_logs', schema='helpdesk') as batch_op:
        batch_op.create_index(batch_op.f('ix_helpdesk_email_logs_ticket_id'), ['ticket_id'], unique=False)

    op.create_table('ticket_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('author_name', sa.String(length=255), nullable=False),
    sa.Column('author_email', sa.String(length=255), nullable=True),
    sa.Column('author_type', sa.String(length=20), nullable=True),
    sa.Column('is_internal', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['helpdesk.tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='helpdesk'
    )
    with op.batch_alter_table('ticket_comments', schema='helpdesk') as batch_op:
        batch_op.create_index(batch_op.f('ix_helpdesk_ticket_comments_ticket_id'), ['ticket_id'], unique=False)

    op.create_table('ticket_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('uploaded_by', sa.String(length=255), nullable=True),
    sa.Column('is_inline', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['helpdesk.ticket_comments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ticket_id'], ['helpdesk.tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='helpdesk'
    )
    with op.batch_alter_table('ticket_attachments', schema='helpdesk') as batch_op:
        batch_op.create_index(batch_op.f('ix_helpdesk_ticket_attachments_ticket_id'), ['ticket_id'], unique=False)

    with op.batch_alter_table('ticket_attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ticket_attachments_ticket_id'))

    op.drop_table('ticket_attachments')
    with op.batch_alter_table('email_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_logs_ticket_id'))

    op.drop_table('email_logs')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_parent_id'))
        batch_op.drop_index(batch_op.f('ix_categories_slug'))

    op.drop_table('categories')
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tickets_asset_id'))
        batch_op.drop_index(batch_op.f('ix_tickets_assigned_to_email'))
        batch_op.drop_index(batch_op.f('ix_tickets_category_id'))
        batch_op.drop_index(batch_op.f('ix_tickets_email_message_id'))
        batch_op.drop_index(batch_op.f('ix_tickets_email_thread_id'))
        batch_op.drop_index(batch_op.f('ix_tickets_number'))
        batch_op.drop_index(batch_op.f('ix_tickets_priority'))
        batch_op.drop_index(batch_op.f('ix_tickets_requester_email'))
        batch_op.drop_index(batch_op.f('ix_tickets_status'))
        batch_op.drop_index(batch_op.f('ix_tickets_subcategory_id'))

    op.drop_table('tickets')
    with op.batch_alter_table('ticket_comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ticket_comments_ticket_id'))

    op.drop_table('ticket_comments')
    op.drop_table('canned_responses')
    with op.batch_alter_table('sla_policies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sla_policies_category_id'))

    op.drop_table('sla_policies')
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assets_category'))
        batch_op.drop_index(batch_op.f('ix_assets_serial_number'))
        batch_op.drop_index(batch_op.f('ix_assets_status'))
        batch_op.create_index(batch_op.f('ix_asset_manager_assets_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_manager_assets_serial_number'), ['serial_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_asset_manager_assets_status'), ['status'], unique=False)

    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assignments_asset_id'))
        batch_op.create_index(batch_op.f('ix_asset_manager_assignments_asset_id'), ['asset_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('assignments_asset_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'assets', ['asset_id'], ['id'], referent_schema='asset_manager')

    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_issues_asset_id'))
        batch_op.drop_index(batch_op.f('ix_issues_status'))
        batch_op.create_index(batch_op.f('ix_asset_manager_issues_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_manager_issues_status'), ['status'], unique=False)
        batch_op.drop_constraint(batch_op.f('issues_asset_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'assets', ['asset_id'], ['id'], referent_schema='asset_manager')

    with op.batch_alter_table('lifecycle_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lifecycle_events_asset_id'))
        batch_op.create_index(batch_op.f('ix_asset_manager_lifecycle_events_asset_id'), ['asset_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('lifecycle_events_asset_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'assets', ['asset_id'], ['id'], referent_schema='asset_manager')

    with op.batch_alter_table('maintenance_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_maintenance_tasks_asset_id'))
        batch_op.create_index(batch_op.f('ix_asset_manager_maintenance_tasks_asset_id'), ['asset_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('maintenance_tasks_asset_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'assets', ['asset_id'], ['id'], referent_schema='asset_manager')

    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('purchase_orders_asset_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'assets', ['asset_id'], ['id'], referent_schema='asset_manager')

    with op.batch_alter_table('repairs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_repairs_asset_id'))
        batch_op.create_index(batch_op.f('ix_asset_manager_repairs_asset_id'), ['asset_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('repairs_issue_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('repairs_asset_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'assets', ['asset_id'], ['id'], referent_schema='asset_manager')
        batch_op.create_foreign_key(None, 'issues', ['issue_id'], ['id'], referent_schema='asset_manager')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('repairs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('repairs_asset_id_fkey'), 'assets', ['asset_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('repairs_issue_id_fkey'), 'issues', ['issue_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_asset_manager_repairs_asset_id'))
        batch_op.create_index(batch_op.f('ix_repairs_asset_id'), ['asset_id'], unique=False)

    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('purchase_orders_asset_id_fkey'), 'assets', ['asset_id'], ['id'])

    with op.batch_alter_table('maintenance_tasks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('maintenance_tasks_asset_id_fkey'), 'assets', ['asset_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_asset_manager_maintenance_tasks_asset_id'))
        batch_op.create_index(batch_op.f('ix_maintenance_tasks_asset_id'), ['asset_id'], unique=False)

    with op.batch_alter_table('lifecycle_events', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('lifecycle_events_asset_id_fkey'), 'assets', ['asset_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_asset_manager_lifecycle_events_asset_id'))
        batch_op.create_index(batch_op.f('ix_lifecycle_events_asset_id'), ['asset_id'], unique=False)

    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('issues_asset_id_fkey'), 'assets', ['asset_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_asset_manager_issues_status'))
        batch_op.drop_index(batch_op.f('ix_asset_manager_issues_asset_id'))
        batch_op.create_index(batch_op.f('ix_issues_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_issues_asset_id'), ['asset_id'], unique=False)

    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('assignments_asset_id_fkey'), 'assets', ['asset_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_asset_manager_assignments_asset_id'))
        batch_op.create_index(batch_op.f('ix_assignments_asset_id'), ['asset_id'], unique=False)

    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asset_manager_assets_status'))
        batch_op.drop_index(batch_op.f('ix_asset_manager_assets_serial_number'))
        batch_op.drop_index(batch_op.f('ix_asset_manager_assets_category'))
        batch_op.create_index(batch_op.f('ix_assets_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_serial_number'), ['serial_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_assets_category'), ['category'], unique=False)

    op.create_table('sla_policies',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('sla_policies_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('priority', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('first_response_hours', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('resolution_hours', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('business_hours_only', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name='sla_policies_category_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='sla_policies_pkey'),
    postgresql_ignore_search_path=False
    )
    with op.batch_alter_table('sla_policies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sla_policies_category_id'), ['category_id'], unique=False)

    op.create_table('canned_responses',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('shortcut', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('subject', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('body', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('use_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('canned_responses_category_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('canned_responses_pkey')),
    sa.UniqueConstraint('shortcut', name=op.f('canned_responses_shortcut_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('ticket_comments',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('ticket_comments_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('ticket_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('body', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('author_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('author_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('author_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('is_internal', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], name='ticket_comments_ticket_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='ticket_comments_pkey'),
    postgresql_ignore_search_path=False
    )
    with op.batch_alter_table('ticket_comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ticket_comments_ticket_id'), ['ticket_id'], unique=False)

    op.create_table('tickets',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('tickets_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('number', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('priority', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('subcategory_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('requester_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('requester_email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('requester_phone', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('assigned_to', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('assigned_to_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('asset_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sla_policy_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('first_response_due', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('resolution_due', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('first_responded_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('tags', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('email_message_id', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('email_thread_id', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('email_cc', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('solved_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('closed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name='tickets_asset_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name='tickets_category_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sla_policy_id'], ['sla_policies.id'], name='tickets_sla_policy_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subcategory_id'], ['categories.id'], name='tickets_subcategory_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='tickets_pkey'),
    postgresql_ignore_search_path=False
    )
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tickets_subcategory_id'), ['subcategory_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tickets_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_tickets_requester_email'), ['requester_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_tickets_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_tickets_number'), ['number'], unique=True)
        batch_op.create_index(batch_op.f('ix_tickets_email_thread_id'), ['email_thread_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tickets_email_message_id'), ['email_message_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_tickets_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tickets_assigned_to_email'), ['assigned_to_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_tickets_asset_id'), ['asset_id'], unique=False)

    op.create_table('categories',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('categories_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('slug', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('color', sa.VARCHAR(length=7), autoincrement=False, nullable=True),
    sa.Column('icon', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('sort_order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], name='categories_parent_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='categories_pkey'),
    sa.UniqueConstraint('name', name='categories_name_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_categories_parent_id'), ['parent_id'], unique=False)

    op.create_table('email_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('direction', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('ticket_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('message_id', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('from_addr', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('to_addr', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('subject', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('error', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('raw_snippet', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], name=op.f('email_logs_ticket_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('email_logs_pkey')),
    sa.UniqueConstraint('message_id', name=op.f('email_logs_message_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    with op.batch_alter_table('email_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_logs_ticket_id'), ['ticket_id'], unique=False)

    op.create_table('ticket_attachments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ticket_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('comment_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('filename', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('original_filename', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('mime_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('uploaded_by', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('is_inline', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['ticket_comments.id'], name=op.f('ticket_attachments_comment_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], name=op.f('ticket_attachments_ticket_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('ticket_attachments_pkey'))
    )
    with op.batch_alter_table('ticket_attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ticket_attachments_ticket_id'), ['ticket_id'], unique=False)

    with op.batch_alter_table('ticket_attachments', schema='helpdesk') as batch_op:
        batch_op.drop_index(batch_op.f('ix_helpdesk_ticket_attachments_ticket_id'))

    op.drop_table('ticket_attachments', schema='helpdesk')
    with op.batch_alter_table('ticket_comments', schema='helpdesk') as batch_op:
        batch_op.drop_index(batch_op.f('ix_helpdesk_ticket_comments_ticket_id'))

    op.drop_table('ticket_comments', schema='helpdesk')
    with op.batch_alter_table('email_logs', schema='helpdesk') as batch_op:
        batch_op.drop_index(batch_op.f('ix_helpdesk_email_logs_ticket_id'))

    op.drop_table('email_logs', schema='helpdesk')
    with op.batch_alter_table('tickets', schema='helpdesk') as batch_op:
        batch_op.drop_index(batch_op.f('ix_helpdesk_tickets_subcategory_id'))
        batch_op.drop_index(batch_op.f('ix_helpdesk_tickets_status'))
        batch_op.drop_index(batch_op.f('ix_helpdesk_tickets_requester_email'))
        batch_op.drop_index(batch_op.f('ix_helpdesk_tickets_priority'))
        batch_op.drop_index(batch_op.f('ix_helpdesk_tickets_number'))
        batch_op.drop_index(batch_op.f('ix_helpdesk_tickets_email_thread_id'))
        batch_op.drop_index(batch_op.f('ix_helpdesk_tickets_email_message_id'))
        batch_op.drop_index(batch_op.f('ix_helpdesk_tickets_category_id'))
        batch_op.drop_index(batch_op.f('ix_helpdesk_tickets_assigned_to_email'))
        batch_op.drop_index(batch_op.f('ix_helpdesk_tickets_asset_id'))

    op.drop_table('tickets', schema='helpdesk')
    with op.batch_alter_table('sla_policies', schema='helpdesk') as batch_op:
        batch_op.drop_index(batch_op.f('ix_helpdesk_sla_policies_category_id'))

    op.drop_table('sla_policies', schema='helpdesk')
    op.drop_table('canned_responses', schema='helpdesk')
    with op.batch_alter_table('categories', schema='helpdesk') as batch_op:
        batch_op.drop_index(batch_op.f('ix_helpdesk_categories_slug'))
        batch_op.drop_index(batch_op.f('ix_helpdesk_categories_parent_id'))

    op.drop_table('categories', schema='helpdesk')
    # ### end Alembic commands ###
